services:
  # ===== MESSAGE QUEUE =====
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ===== SHARED DATABASE =====
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: ecom
      POSTGRES_USER: ecom
      POSTGRES_PASSWORD: ecom
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecom"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ===== MICROSERVICES =====
  
  # Auth Service
  auth-service:
    build:
      context: ./apps/auth-service
      dockerfile: Dockerfile.dev
    container_name: auth-service
    command: npm run start:dev
    env_file: .env
    environment:
      # Override with specific values
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ecom
      DB_USER: ecom
      DB_PASS: ecom
    ports:
      - "3001:3001"
    volumes:
      - ./apps/auth-service:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy

  # Order Worker
  order-worker:
    build:
      context: ./apps/order-worker
      dockerfile: Dockerfile.dev
    container_name: order-worker
    command: npm run start:dev
    env_file: .env
    environment:
      PORT: 3002
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ecom
      DB_USER: ecom
      DB_PASS: ecom
    ports:
      - "3002:3002"
    volumes:
      - ./apps/order-worker:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  # API Gateway
  api-gateway:
    build:
      context: ./apps/api-gateway
      dockerfile: Dockerfile.dev
    container_name: api-gateway
    env_file: .env
    environment:
      # Override with specific values
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ecom
      DB_USER: ecom
      DB_PASS: ecom
      AUTH_SERVICE_URL: http://auth-service:3001
      ORDER_SERVICE_URL: http://order-worker:3002
    ports:
      - "3000:3000"
    volumes:
      - ./apps/api-gateway:/app
      - /app/node_modules
    depends_on:
      auth-service:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy

volumes:
  pgdata: